services:
    postgres:
        image: postgres:16-alpine
        container_name: crud_db
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres 
            POSTGRES_DB: crud
        ports:
            - "5433:5432"
        volumes:
            - "postgres_data:/var/lib/postgresql/data"
        restart: unless-stopped

volumes: 
    postgres_data: